INSERT INTO shopping_list (name, price, category, checked, date_added)
VALUES
  ('Lunch 1', 23, 'Lunch',false, now()),
  ('Main 8', 5.38, 'Main', true,  now()),
  ('Main 9', 4.20, 'Main', false, now()),
  ('Main 1', 13.33, 'Main', false, now() - '7 days'::INTERVAL),
  ('Snack 3', 4.99, 'Snack', true,  now() - '7 days'::INTERVAL),
  ('Snack 4', 5.44, 'Snack', false, now() - '14 days'::INTERVAL),
  ('Lunch 6', 1.44, 'Lunch',  false, now() - '7 days'::INTERVAL),
  ('Lunch 3 ', 0.20, 'Lunch',  true,  now() - '14 days'::INTERVAL),
  ('Lunch 4', 1.80, 'Lunch', true,  now() - '7 days'::INTERVAL),
  ('Main 2', 1.50, 'Main', false, now() - '7 days'::INTERVAL),
  ('Lunch 6', 3.45, 'Lunch', false, now() - '14 days'::INTERVAL),
  ('Breakfast 7', 1.20, 'Breakfast',  false, now() - '14 days'::INTERVAL),
  ('Lunch 45', 0.36, 'Lunch',  true,  now() - '14 days'::INTERVAL),
  ('Breakfast 4', 1.4, 'Breakfast',  false, now() - '14 days'::INTERVAL),
  ('Main 78', 3.50, 'Main',  false, now() - '21 days'::INTERVAL),
  ('Breakfast 34', 1.30, 'Breakfast',  false, now() - '21 days'::INTERVAL),
  ('Snack 343', 3.50, 'Snack', false, now() - '21 days'::INTERVAL),
  ('Main 3', 7.5, 'Main',false, now() - '21 days'::INTERVAL),
  ('Main 4', 4.35, 'Main',  false, now() - '3 days'::INTERVAL),
  ('Main 5', 5.25, 'Main', false, now() - '7 days'::INTERVAL),
  ('Snack 23', 6.3, 'Snack',false, now() - '7 days'::INTERVAL),
  ('Breakfast 43', 7.5, 'Breakfast', false, now() - '7 days'::INTERVAL),
  ('Main 6', 6.80, 'Main', false, now() - '7 days'::INTERVAL),
  ('Lunch 34', 2.4, 'Lunch', false, now() - '21 days'::INTERVAL),
  ('Lunch 342', 4.5, 'Lunch',  false, now() - '21 days'::INTERVAL),
  ('Main 7', 8.45, 'Main',  false, now() - '21 days'::INTERVAL);